#pragma once

#include "driver/gpio.h"
#include "driver/i2c_types.h"
#include "driver/i2s_types.h"
#include "esp_lcd_panel_vendor.h"

#define BOARD_LCD_H_RES 320
#define BOARD_LCD_V_RES 320
#define BOARD_LCD_DATA_WIDTH 8
#define BOARD_LCD_PIXEL_CLOCK_HZ (10 * 1000 * 1000)
#define BOARD_LCD_DRAW_LINES 16
#define BOARD_LCD_RS GPIO_NUM_18
#define BOARD_LCD_WR GPIO_NUM_17
#define BOARD_LCD_CS GPIO_NUM_19
#define BOARD_LCD_RST GPIO_NUM_35
#define BOARD_LCD_BL GPIO_NUM_16
#define BOARD_LCD_D0 GPIO_NUM_44
#define BOARD_LCD_D1 GPIO_NUM_43
#define BOARD_LCD_D2 GPIO_NUM_42
#define BOARD_LCD_D3 GPIO_NUM_40
#define BOARD_LCD_D4 GPIO_NUM_39
#define BOARD_LCD_D5 GPIO_NUM_38
#define BOARD_LCD_D6 GPIO_NUM_37
#define BOARD_LCD_D7 GPIO_NUM_36
#define BOARD_LCD_RGB_ORDER LCD_RGB_ELEMENT_ORDER_BGR
#define BOARD_LCD_INVERT_COLOR 1
#define BOARD_LCD_SWAP_XY 0
#define BOARD_LCD_MIRROR_X 1
#define BOARD_LCD_MIRROR_Y 0
#define BOARD_LCD_SOFTWARE_ROTATE_CW_90 1

#define BOARD_I2C_PORT I2C_NUM_0
#define BOARD_I2C_SDA GPIO_NUM_0
#define BOARD_I2C_SCL GPIO_NUM_1
#define BOARD_I2C_FREQ_HZ 400000

#define BOARD_XL9555_ADDR 0x22
#define BOARD_XL9555_PIN(port, pin) (1U << ((port) * 8 + (pin)))
#define BOARD_XL_P00_TOUCH_INT BOARD_XL9555_PIN(0, 0)
#define BOARD_XL_P01_TOUCH_RST BOARD_XL9555_PIN(0, 1)
#define BOARD_XL_P02_CHARGE_NCE BOARD_XL9555_PIN(0, 2)
#define BOARD_XL_P03_CHARGE_INT BOARD_XL9555_PIN(0, 3)
#define BOARD_XL_P04_CHARGE_PG BOARD_XL9555_PIN(0, 4)
#define BOARD_XL_P05_5V_EN BOARD_XL9555_PIN(0, 5)
#define BOARD_XL_P07_SPK_EN BOARD_XL9555_PIN(0, 7)
#define BOARD_XL_P10_SD_EN BOARD_XL9555_PIN(1, 0)
#define BOARD_XL_P11_DRV_EN BOARD_XL9555_PIN(1, 1)
#define BOARD_XL_OUTPUT_MASK (BOARD_XL_P01_TOUCH_RST | BOARD_XL_P02_CHARGE_NCE | \
                              BOARD_XL_P05_5V_EN | BOARD_XL_P07_SPK_EN | \
                              BOARD_XL_P10_SD_EN | BOARD_XL_P11_DRV_EN)
#define BOARD_XL_SAFE_HIGH_MASK (BOARD_XL_P01_TOUCH_RST | BOARD_XL_P02_CHARGE_NCE)
#define BOARD_XL_SAFE_LOW_MASK (BOARD_XL_OUTPUT_MASK & ~BOARD_XL_SAFE_HIGH_MASK)

#define BOARD_TOUCH_ADDR 0x38
#define BOARD_TOUCH_PAD GPIO_NUM_11
#define BOARD_GPIO60 GPIO_NUM_60
#define BOARD_BOOT_PIN GPIO_NUM_61
#define BOARD_TOUCH_RAW_RES 240
#define BOARD_TOUCH_THRESHOLD 25
#define BOARD_TOUCH_REPORT_RATE_HZ 30
// Inverse of the display's software CW rotation: logical=(y, 319-x).
// esp_lcd_touch applies mirrors before swapping axes.
#define BOARD_TOUCH_SWAP_XY 1
#define BOARD_TOUCH_MIRROR_X 1
#define BOARD_TOUCH_MIRROR_Y 0

#define BOARD_ES8389_ADDR 0x10
#define BOARD_ES7210_ADDR 0x40
#define BOARD_I2S_PORT I2S_NUM_0
#define BOARD_I2S_MCLK GPIO_NUM_6
#define BOARD_I2S_DOUT GPIO_NUM_7
#define BOARD_I2S_BCLK GPIO_NUM_8
#define BOARD_I2S_LRCK GPIO_NUM_9
#define BOARD_I2S_DIN GPIO_NUM_10
#define BOARD_AUDIO_SAMPLE_RATE 48000
#define BOARD_AUDIO_CHANNELS 2
#define BOARD_AUDIO_MCLK_MULTIPLE I2S_MCLK_MULTIPLE_256

#define BOARD_CAMERA_PMIC_ADDR 0x28
#define BOARD_CAMERA_I2C_PORT I2C_NUM_1
#define BOARD_CAMERA_SDA GPIO_NUM_3
#define BOARD_CAMERA_SCL GPIO_NUM_4
#define BOARD_CAMERA_RESET GPIO_NUM_45
#define BOARD_CAMERA_D0 GPIO_NUM_46
#define BOARD_CAMERA_D1 GPIO_NUM_47
#define BOARD_CAMERA_D2 GPIO_NUM_48
#define BOARD_CAMERA_D3 GPIO_NUM_49
#define BOARD_CAMERA_D4 GPIO_NUM_50
#define BOARD_CAMERA_D5 GPIO_NUM_51
#define BOARD_CAMERA_D6 GPIO_NUM_52
#define BOARD_CAMERA_D7 GPIO_NUM_53
#define BOARD_CAMERA_PCLK GPIO_NUM_54
#define BOARD_CAMERA_XCLK GPIO_NUM_55
#define BOARD_CAMERA_HREF GPIO_NUM_57
#define BOARD_CAMERA_XCLK_HZ (20 * 1000 * 1000)
#define BOARD_CAMERA_JPEG_QUALITY 8

#define BOARD_CHARGER_ADDR 0x6B
#define BOARD_SERVO_PWM GPIO_NUM_5
#define BOARD_DRV_BIN2 GPIO_NUM_12
#define BOARD_DRV_BIN1 GPIO_NUM_13
#define BOARD_DRV_AIN2 GPIO_NUM_14
#define BOARD_DRV_AIN1 GPIO_NUM_15

#define BOARD_SD_D0 GPIO_NUM_20
#define BOARD_SD_D1 GPIO_NUM_21
#define BOARD_SD_D2 GPIO_NUM_22
#define BOARD_SD_D3 GPIO_NUM_23
#define BOARD_SD_CLK GPIO_NUM_24
#define BOARD_SD_CMD GPIO_NUM_25
#define BOARD_SD_MOUNT_POINT "/sdcard"
