#pragma once

#if __has_include("factory_config.h")
#include "factory_config.h"
#endif

#ifndef FACTORY_WIFI_SSID
#define FACTORY_WIFI_SSID ""
#endif
#ifndef FACTORY_WIFI_PASSWORD
#define FACTORY_WIFI_PASSWORD ""
#endif
#ifndef FACTORY_WIFI_MIN_RSSI_DBM
#define FACTORY_WIFI_MIN_RSSI_DBM (-70)
#endif
#ifndef FACTORY_MIC_MIN_DBFS
#define FACTORY_MIC_MIN_DBFS (-45.0f)
#endif
#ifndef FACTORY_MANUAL_TIMEOUT_MS
#define FACTORY_MANUAL_TIMEOUT_MS 30000
#endif

#define FACTORY_DEVICE_NAME "T-Bao-S31"
#define FACTORY_RESULT_SCHEMA 1
#define FACTORY_TOUCH_TIMEOUT_MS 30000
#define FACTORY_CAMERA_FRAME_TARGET 30
#define FACTORY_CHARGER_VBUS_MIN_MV 4400
#define FACTORY_CHARGER_VBAT_MIN_MV 5000
#define FACTORY_CHARGER_VBAT_MAX_MV 8600
#define FACTORY_CHARGER_VREG_MV 8400
#define FACTORY_CHARGER_CURRENT_MA 500
